"""Update principal, arreglado error de formato

Revision ID: 8baf3ddb5314
Revises: c4b73914ad02
Create Date: 2023-05-13 16:29:37.078425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baf3ddb5314'
down_revision = 'c4b73914ad02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_team_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('player_team_name_key', ['team_name'])

    # ### end Alembic commands ###
