"""Add Split table and split_id columns

Revision ID: bc569f22c047
Revises: 
Create Date: 2023-05-08 00:11:17.313503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc569f22c047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS team CASCADE")
    op.drop_table('match')
    op.drop_table('player')
    op.drop_table('matchday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchday',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('matchday_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='matchday_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posicion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partidos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goles_encajados', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penaltis_parados', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('t_amarilla', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('t_roja', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mvp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goles', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asist', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reflejo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paradas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saque', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estirada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('velocidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fisico', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tiro', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pase', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('talento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('defensa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='player_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_pkey')
    )
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('matchday_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], name='match_away_team_id_fkey'),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], name='match_home_team_id_fkey'),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], name='match_matchday_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('presidente', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entrenador', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jugador_11', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jugador_12_nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jugador_12_posicion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jugador_13_nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jugador_13_posicion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('victorias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('victorias_penaltis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derrotas_penaltis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derrotas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goles_favor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goles_contra', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diferencia_goles', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='team_pkey')
    )
    # ### end Alembic commands ###
