"""empty message

Revision ID: 916a76726bd9
Revises: 
Create Date: 2023-05-13 15:32:17.165930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916a76726bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(), nullable=False),
    sa.Column('away_team_name', sa.String(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['split.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('victories', sa.Integer(), nullable=True),
    sa.Column('penalty_victories', sa.Integer(), nullable=True),
    sa.Column('penalty_defeats', sa.Integer(), nullable=True),
    sa.Column('defeats', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('goals_difference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['split_id'], ['split.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('split')
    op.drop_table('matchday')
    # ### end Alembic commands ###
